# Generated by Django 3.2 on 2021-04-29 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='p_challenge',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitment',
            name='p_commitment',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='composure',
            name='p_composure',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concentration',
            name='p_concentration',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confidence',
            name='p_confidence',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
